import { motion } from 'framer-motion';
import { FileText } from 'lucide-react';

const ease = [0.22, 1, 0.36, 1] as const;
const LAST_UPDATED = 'August 28, 2026';

const sections = [
  {
    title: 'Acceptance of terms',
    body: [
      'By accessing or using Toolorna, you agree to these terms and conditions. If you do not agree, please do not use the website.',
    ],
  },
  {
    title: 'Educational and informational purpose',
    body: [
      'All content on Toolorna — including the guide, scenarios, and Ask Toolorna responses — is provided for informational and educational purposes only.',
      'Nothing on this website is professional psychological, medical, or therapeutic advice. The stories, tips, and AI-generated responses are general guidance meant to help you think through common relationship situations. They are not a substitute for professional help.',
      'Always seek the advice of a qualified professional for matters related to your mental health, relationships, or safety. Never disregard professional advice or delay seeking it because of something you read on Toolorna.',
    ],
  },
  {
    title: 'No guarantees',
    body: [
      'Human relationships are complex and unpredictable. We cannot and do not guarantee that following any advice on Toolorna will lead to a specific outcome. Use your own judgement, read the situation, and respect the other person\'s feelings and choices.',
    ],
  },
  {
    title: 'Consent and respect',
    body: [
      'Toolorna does not support or endorse manipulation, pressure, coercion, stalking, or any form of non-consensual behaviour. If any content on this site is used to harm, pressure, or deceive another person, that use is a violation of these terms and is not what Toolorna is for.',
    ],
  },
  {
    title: 'AI-generated content',
    body: [
      'Responses from Ask Toolorna are generated by an AI model and may be inaccurate, incomplete, or inappropriate. Do not rely on them as professional advice. Use your own judgement and, for anything serious, speak to someone you trust or a professional.',
    ],
  },
  {
    title: 'Distress and safety',
    body: [
      'If you are in distress, experiencing abuse, or having thoughts of self-harm, please reach out to a trusted person, a mental health professional, or a helpline. Toolorna is not equipped to handle crisis situations.',
    ],
  },
  {
    title: 'Purchases',
    body: [
      'Products sold through the Shop are digital goods. Due to the nature of digital downloads, refunds are generally not available once a file has been accessed or downloaded. If you experience a genuine issue accessing your purchase, contact us at allearnhelp@gmail.com and we will help.',
    ],
  },
  {
    title: 'Intellectual property',
    body: [
      'The content on Toolorna — including text, scenarios, guide material, and design — is owned by Toolorna. You may not copy, redistribute, or republish our content without permission. Purchased digital products are for your personal use only and may not be shared or resold.',
    ],
  },
  {
    title: 'Limitation of liability',
    body: [
      'Toolorna is provided "as is" without warranties of any kind. To the fullest extent permitted by law, we are not liable for any damages arising from your use of the website or reliance on its content.',
    ],
  },
  {
    title: 'Changes to these terms',
    body: [
      'We may update these terms from time to time. The date at the top of this page reflects the last update. Continued use of the site after changes means you accept the updated terms.',
    ],
  },
  {
    title: 'Contact',
    body: [
      'Questions about these terms? Email us at allearnhelp@gmail.com.',
    ],
  },
];

export function Terms() {
  return (
    <div className="mx-auto max-w-3xl px-5 sm:px-8 py-12 sm:py-20">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease }}
        className="mb-10"
      >
        <div className="inline-flex items-center gap-2 mb-3">
          <FileText className="w-4 h-4" strokeWidth={1.75} style={{ color: 'var(--color-romance)' }} />
          <p className="font-mono text-xs tracking-[0.2em] uppercase text-faint">Terms</p>
        </div>
        <h1 className="font-display text-3xl sm:text-5xl font-700 text-heading mb-3">
          Terms &amp; Disclaimer
        </h1>
        <p className="font-mono text-xs text-faint">Last updated: {LAST_UPDATED}</p>
      </motion.div>

      <div className="space-y-8">
        {sections.map((s, i) => (
          <motion.section
            key={i}
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.4, ease }}
          >
            <h2 className="font-display text-lg sm:text-xl font-700 text-heading mb-3">{s.title}</h2>
            <div className="space-y-3">
              {s.body.map((p, j) => (
                <p key={j} className="font-body text-[15px] text-body leading-[1.75]">{p}</p>
              ))}
            </div>
          </motion.section>
        ))}
      </div>
    </div>
  );
}
